package com.dp.gestiondemuna.entity;

import java.io.Serializable;
import java.util.Date;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.hibernate.annotations.Formula;
import org.springframework.format.annotation.DateTimeFormat;

@Entity
@Data
@NoArgsConstructor
@Table(name = "educa_ficha_s8", schema = "SIGA")
public class Demuna_Ficha_S8Entity implements Serializable {
    @Id
    public Integer id_ficha_s8;
    public Integer id_ficha;
    private String usu_registro;

    @DateTimeFormat(pattern = "dd/MM/yyyy HH:mm:ss")
    @Temporal(TemporalType.TIMESTAMP)
    private Date fch_registro;

    private String usu_actualiza;

    @DateTimeFormat(pattern = "dd/MM/yyyy HH:mm:ss")
    @Temporal(TemporalType.TIMESTAMP)
    private Date fch_actualiza;
    private String estado_s8;

    private Integer p8_1_pc_cant_total;
    private Integer p8_1_pc_total_operativa1;
    private Integer p8_1_pc_estado2_estado;
    private Integer p8_1_pc_estado2_reparacion;
    private Integer p8_1_pc_educativo3_menos5;
    private Integer p8_1_pc_educativo3_ma5;
    private Integer p8_1_pc_conec_aula;
    private Integer p8_1_pc_conec_pedago;
    private Integer p8_1_pc_conec_taller;
    private Integer p8_1_pc_conec_otros;
    private Integer p8_1_pc_wifi_aula;
    private Integer p8_1_pc_wifi_pedago;
    private Integer p8_1_pc_wifi_taller;
    private Integer p8_1_pc_wifi_otros;
    private Integer p8_1_pc_no_conec_aula;
    private Integer p8_1_pc_no_conec_pedago;
    private Integer p8_1_pc_no_conec_taller;
    private Integer p8_1_pc_no_conec_otros;
    private Integer p8_1_lapt_cant_total;
    private Integer p8_1_lapt_total_operativa1;
    private Integer p8_1_lapt_estado2_estado;
    private Integer p8_1_lapt_estado2_reparacion;
    private Integer p8_1_lapt_educativo3_menos5;
    private Integer p8_1_lapt_educativo3_ma5;
    private Integer p8_1_lapt_conec_aula;
    private Integer p8_1_lapt_conec_pedago;
    private Integer p8_1_lapt_conec_taller;
    private Integer p8_1_lapt_conec_otros;
    private Integer p8_1_lapt_wifi_aula;
    private Integer p8_1_lapt_wifi_pedago;
    private Integer p8_1_lapt_wifi_taller;
    private Integer p8_1_lapt_wifi_otros;
    private Integer p8_1_lapt_no_conec_aula;
    private Integer p8_1_lapt_no_conec_pedago;
    private Integer p8_1_lapt_no_conec_taller;
    private Integer p8_1_lapt_no_conec_otros;
    private Integer p8_1_xo_cant_total;
    private Integer p8_1_xo_total_operativa1;
    private Integer p8_1_xo_estado2_estado;
    private Integer p8_1_xo_estado2_reparacion;
    private Integer p8_1_xo_educativo3_menos5;
    private Integer p8_1_xo_educativo3_ma5;
    private Integer p8_1_xo_conec_aula;
    private Integer p8_1_xo_conec_pedago;
    private Integer p8_1_xo_conec_taller;
    private Integer p8_1_xo_conec_otros;
    private Integer p8_1_xo_wifi_aula;
    private Integer p8_1_xo_wifi_pedago;
    private Integer p8_1_xo_wifi_taller;
    private Integer p8_1_xo_wifi_otros;
    private Integer p8_1_xo_no_conec_aula;
    private Integer p8_1_xo_no_conec_pedago;
    private Integer p8_1_xo_no_conec_taller;
    private Integer p8_1_xo_no_conec_otros;

    private Integer p8_1_casa_cant_total;
    private Integer p8_1_casa_total_operativa1;
    private Integer p8_1_casa_estado2_estado;
    private Integer p8_1_casa_estado2_reparacion;
    private Integer p8_1_casa_educativo3_menos5;
    private Integer p8_1_casa_educativo3_ma5;
    private Integer p8_1_casa_conec_aula;
    private Integer p8_1_casa_conec_pedago;
    private Integer p8_1_casa_conec_taller;
    private Integer p8_1_casa_conec_otros;
    private Integer p8_1_casa_wifi_aula;
    private Integer p8_1_casa_wifi_pedago;
    private Integer p8_1_casa_wifi_taller;
    private Integer p8_1_casa_wifi_otros;
    private Integer p8_1_casa_no_conec_aula;
    private Integer p8_1_casa_no_conec_pedago;
    private Integer p8_1_casa_no_conec_taller;
    private Integer p8_1_casa_no_conec_otros;
    private Integer p8_1_pro_cant_total;
    private Integer p8_1_pro_total_operativa1;
    private Integer p8_1_pro_estado2_estado;
    private Integer p8_1_pro_estado2_reparacion;
    private Integer p8_1_pro_educativo3_menos5;
    private Integer p8_1_pro_educativo3_ma5;
    private Integer p8_1_pro_conec_aula;
    private Integer p8_1_pro_conec_pedago;
    private Integer p8_1_pro_conec_taller;
    private Integer p8_1_pro_conec_otros;
    private Integer p8_1_pro_wifi_aula;
    private Integer p8_1_pro_wifi_pedago;
    private Integer p8_1_pro_wifi_taller;
    private Integer p8_1_pro_wifi_otros;
    private Integer p8_1_pro_no_conec_aula;
    private Integer p8_1_pro_no_conec_pedago;
    private Integer p8_1_pro_no_conec_taller;
    private Integer p8_1_pro_no_conec_otros;
    private Integer p8_1_otro_cant_total;
    private Integer p8_1_otro_total_operativa1;
    private Integer p8_1_otro_estado2_estado;
    private Integer p8_1_otro_estado2_reparacion;
    private Integer p8_1_otro_educativo3_menos5;
    private Integer p8_1_otro_educativo3_ma5;
    private Integer p8_1_otro_conec_aula;
    private Integer p8_1_otro_conec_pedago;
    private Integer p8_1_otro_conec_taller;
    private Integer p8_1_otro_conec_otros;
    private Integer p8_1_otro_wifi_aula;
    private Integer p8_1_otro_wifi_pedago;
    private Integer p8_1_otro_wifi_taller;
    private Integer p8_1_otro_wifi_otros;
    private Integer p8_1_otro_no_conec_aula;
    private Integer p8_1_otro_no_conec_pedago;
    private Integer p8_1_otro_no_conec_taller;
    private Integer p8_1_otro_no_conec_otros;
    private Integer p8_1_multi_cant_total;
    private Integer p8_1_multi_total_operativa1;
    private Integer p8_1_multi_estado2_estado;
    private Integer p8_1_multi_estado2_reparacion;
    private Integer p8_1_multi_educativo3_menos5;
    private Integer p8_1_multi_educativo3_ma5;
    private Integer p8_1_multi_conec_aula;
    private Integer p8_1_multi_conec_pedago;
    private Integer p8_1_multi_conec_taller;
    private Integer p8_1_multi_conec_otros;
    private Integer p8_1_multi_wifi_aula;
    private Integer p8_1_multi_wifi_pedago;
    private Integer p8_1_multi_wifi_taller;
    private Integer p8_1_multi_wifi_otros;
    private Integer p8_1_multi_no_conec_aula;
    private Integer p8_1_multi_no_conec_pedago;
    private Integer p8_1_multi_no_conec_taller;
    private Integer p8_1_multi_no_conec_otros;
    private Integer p8_1_piza_cant_total;
    private Integer p8_1_piza_total_operativa1;
    private Integer p8_1_piza_estado2_estado;
    private Integer p8_1_piza_estado2_reparacion;
    private Integer p8_1_piza_educativo3_menos5;
    private Integer p8_1_piza_educativo3_ma5;
    private Integer p8_1_piza_conec_aula;
    private Integer p8_1_piza_conec_pedago;
    private Integer p8_1_piza_conec_taller;
    private Integer p8_1_piza_conec_otros;
    private Integer p8_1_piza_wifi_aula;
    private Integer p8_1_piza_wifi_pedago;
    private Integer p8_1_piza_wifi_taller;
    private Integer p8_1_piza_wifi_otros;
    private Integer p8_1_piza_no_conec_aula;
    private Integer p8_1_piza_no_conec_pedago;
    private Integer p8_1_piza_no_conec_taller;
    private Integer p8_1_piza_no_conec_otros;
    private Integer p8_1_auri_cant_total;
    private Integer p8_1_auri_total_operativa1;
    private Integer p8_1_auri_estado2_estado;
    private Integer p8_1_auri_estado2_reparacion;
    private Integer p8_1_auri_educativo3_menos5;
    private Integer p8_1_auri_educativo3_ma5;
    private Integer p8_1_auri_conec_aula;
    private Integer p8_1_auri_conec_pedago;
    private Integer p8_1_auri_conec_taller;
    private Integer p8_1_auri_conec_otros;
    private Integer p8_1_auri_wifi_aula;
    private Integer p8_1_auri_wifi_pedago;
    private Integer p8_1_auri_wifi_taller;
    private Integer p8_1_auri_wifi_otros;
    private Integer p8_1_auri_no_conec_aula;
    private Integer p8_1_auri_no_conec_pedago;
    private Integer p8_1_auri_no_conec_taller;
    private Integer p8_1_auri_no_conec_otros;
    private Integer p8_2_tv_cant_total;
    private Integer p8_2_tv_total_operat;
    private Integer p8_2_tv_buen_estado;
    private Integer p8_2_tv_reparacion;
    private Integer p8_2_tv_menos5;
    private Integer p8_2_tv_mas5;
    private Integer p8_2_tv_aula;
    private Integer p8_2_tv_pedago;
    private Integer p8_2_tv_taller;
    private Integer p8_2_tv_otro;
    private Integer p8_2_dvd_cant_total;
    private Integer p8_2_dvd_total_operat;
    private Integer p8_2_dvd_buen_estado;
    private Integer p8_2_dvd_reparacion;
    private Integer p8_2_dvd_menos5;
    private Integer p8_2_dvd_mas5;
    private Integer p8_2_dvd_aula;
    private Integer p8_2_dvd_pedago;
    private Integer p8_2_dvd_taller;
    private Integer p8_2_dvd_otro;
    private Integer p8_2_radio_cant_total;
    private Integer p8_2_radio_total_operat;
    private Integer p8_2_radio_buen_estado;
    private Integer p8_2_radio_reparacion;
    private Integer p8_2_radio_menos5;
    private Integer p8_2_radio_mas5;
    private Integer p8_2_radio_aula;
    private Integer p8_2_radio_pedago;
    private Integer p8_2_radio_taller;
    private Integer p8_2_radio_otro;
    private Integer p8_2_equip_cant_total;
    private Integer p8_2_equip_total_operat;
    private Integer p8_2_equip_buen_estado;
    private Integer p8_2_equip_reparacion;
    private Integer p8_2_equip_menos5;
    private Integer p8_2_equip_mas5;
    private Integer p8_2_equip_aula;
    private Integer p8_2_equip_pedago;
    private Integer p8_2_equip_taller;
    private Integer p8_2_equip_otro;
    private Integer p8_2_parlan_cant_total;
    private Integer p8_2_parlan_total_operat;
    private Integer p8_2_parlan_buen_estado;
    private Integer p8_2_parlan_reparacion;
    private Integer p8_2_parlan_menos5;
    private Integer p8_2_parlan_mas5;
    private Integer p8_2_parlan_aula;
    private Integer p8_2_parlan_pedago;
    private Integer p8_2_parlan_taller;
    private Integer p8_2_parlan_otro;
    private Integer p8_2_fotoc_cant_total;
    private Integer p8_2_fotoc_total_operat;
    private Integer p8_2_fotoc_buen_estado;
    private Integer p8_2_fotoc_reparacion;
    private Integer p8_2_fotoc_menos5;
    private Integer p8_2_fotoc_mas5;
    private Integer p8_2_fotoc_aula;
    private Integer p8_2_fotoc_pedago;
    private Integer p8_2_fotoc_taller;
    private Integer p8_2_fotoc_otro;
    private Integer p8_2_scan_cant_total;
    private Integer p8_2_scan_total_operat;
    private Integer p8_2_scan_buen_estado;
    private Integer p8_2_scan_reparacion;
    private Integer p8_2_scan_menos5;
    private Integer p8_2_scan_mas5;
    private Integer p8_2_scan_aula;
    private Integer p8_2_scan_pedago;
    private Integer p8_2_scan_taller;
    private Integer p8_2_scan_otro;
    private Integer p8_2_impre_cant_total;
    private Integer p8_2_impre_total_operat;
    private Integer p8_2_impre_buen_estado;
    private Integer p8_2_impre_reparacion;
    private Integer p8_2_impre_menos5;
    private Integer p8_2_impre_mas5;
    private Integer p8_2_impre_aula;
    private Integer p8_2_impre_pedago;
    private Integer p8_2_impre_taller;
    private Integer p8_2_impre_otro;
    private Integer p8_2_multi_cant_total;
    private Integer p8_2_multi_total_operat;
    private Integer p8_2_multi_buen_estado;
    private Integer p8_2_multi_reparacion;
    private Integer p8_2_multi_menos5;
    private Integer p8_2_multi_mas5;
    private Integer p8_2_multi_aula;
    private Integer p8_2_multi_pedago;
    private Integer p8_2_multi_taller;
    private Integer p8_2_multi_otro;
    private Integer p8_2_ecran_cant_total;
    private Integer p8_2_ecran_total_operat;
    private Integer p8_2_ecran_buen_estado;
    private Integer p8_2_ecran_reparacion;
    private Integer p8_2_ecran_menos5;
    private Integer p8_2_ecran_mas5;
    private Integer p8_2_ecran_aula;
    private Integer p8_2_ecran_pedago;
    private Integer p8_2_ecran_taller;
    private Integer p8_2_ecran_otro;
    private Integer p8_2_clima_cant_total;
    private Integer p8_2_clima_total_operat;
    private Integer p8_2_clima_buen_estado;
    private Integer p8_2_clima_reparacion;
    private Integer p8_2_clima_menos5;
    private Integer p8_2_clima_mas5;
    private Integer p8_2_clima_aula;
    private Integer p8_2_clima_pedago;
    private Integer p8_2_clima_taller;
    private Integer p8_2_clima_otro;
    private Integer p8_2_extra_cant_total;
    private Integer p8_2_extra_total_operat;
    private Integer p8_2_extra_buen_estado;
    private Integer p8_2_extra_reparacion;
    private Integer p8_2_extra_menos5;
    private Integer p8_2_extra_mas5;
    private Integer p8_2_extra_aula;
    private Integer p8_2_extra_pedago;
    private Integer p8_2_extra_taller;
    private Integer p8_2_extra_otro;


}